<html>
<head>
<title>Handling JavaScript errors in React with error boundaries - LogRocket Blog</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1>在 React with error boundaries-log rocket 博客中处理 JavaScript 错误</h1>
<blockquote>原文：<a href="https://blog.logrocket.com/handling-javascript-errors-react-error-boundaries/#0001-01-01">https://blog.logrocket.com/handling-javascript-errors-react-error-boundaries/#0001-01-01</a></blockquote><div><article class="article-post">
<p>错误是发展不可避免的一部分。它们似乎总是在最不合适的时候出现，以确保我们的应用程序不会像预期的那样工作。不管它们如何进入我们的代码，错误处理都是对这些无意的开发混乱的解药，更好的理解是异常。</p>
<p>在常规 JavaScript 中，<code>try…catch</code>语句提供了一个 API，我们可以用它来尝试并优雅地捕捉潜在的易错代码:</p>
<pre>try {
  console.log(p)
} catch (error) {
  console.log(`Error: ${error}`) // ReferenceError: p is not defined 
}
</pre>
<p>在<code>try</code>块中检测到的任何错误都会作为异常抛出，并在<code>catch</code>块中被捕获，从而使我们的应用程序对错误更有弹性。在 React 中，这个构造可以很好地处理 JavaScript 错误，如下所示，其中我们用<code>useEffect</code>获取数据:</p>
<pre>useEffect(() =&gt; {
  try {
    fetchUsers();
  } catch(error) {
    setError(error);
  }
}, []);
</pre>
<p>但是这在 React 组件中并不那么有效。</p>
<h2 id="h2whytrycatchdoesntcatchjavascripterrorsinreactcomponents">为什么<code>try...catch</code>不能捕捉 React 组件中的 JavaScript 错误</h2>
<p>认为凭借它的功能和工作方式，<code>try...catch</code>语句可以用来捕捉 React 组件中的 JavaScript 错误是错误的。这是因为<code>try...catch</code>语句只适用于命令式代码，而不是组件中的<a href="https://blog.logrocket.com/writing-readability-declarative-arrays/">声明式代码</a>。</p>
<pre>function ErrorFallbackUI({ errorMessage }) {
  return (
    &lt;div className="article-error"&gt;
      &lt;h3&gt;There was a problem displaying the article:&lt;/h3&gt;
      &lt;h3 className="error"&gt;{errorMessage}&lt;/h3&gt;
    &lt;/div&gt;
  );
}

// There's an attempt to uppercase each publication title
function Publication({ publication }) {
  return (
    &lt;a href={publication.href} className="article-cta"&gt;
      &lt;h3 className="title"&gt;{publication.title.toUpperCase()}&lt;/h3&gt;
      &lt;h3 className="info"&gt;{publication.lead}&lt;/h3&gt;
    &lt;/a&gt;
  );
}

// Map over the list of publications and try to render a &lt;Publication/&gt;
function Publications({ publications }) {
  try {
    return publications.map((publication, index) =&gt; (
      &lt;div key={index}&gt;
        &lt;Publication {...{ publication }} /&gt;
      &lt;/div&gt;
    ));
  } catch (error) {
    return &lt;ErrorFallbackUI {...{ errorMessage: error.errorMessage }} /&gt;;
  }
}
</pre>
<figure id="attachment_38372" aria-describedby="caption-attachment-38372" class="wp-caption aligncenter"><img data-attachment-id="38372" data-permalink="https://blog.logrocket.com/handling-javascript-errors-react-error-boundaries/try-catch-javascript-error-fail-message/" data-orig-file="https://blog.logrocket.com/wp-content/uploads/2021/03/try-catch-javascript-error-fail-message.png" data-orig-size="730,216" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="try-catch-javascript-error-fail-message" data-image-description="" data-image-caption="&lt;p&gt;This error fallback UI has been clipped to show the relevant part. Dismiss the error UI to view the normal state of the application.&lt;/p&gt;&#10;" data-medium-file="https://blog.logrocket.com/wp-content/uploads/2021/03/try-catch-javascript-error-fail-message-300x89.png" data-large-file="https://blog.logrocket.com/wp-content/uploads/2021/03/try-catch-javascript-error-fail-message.png" decoding="async" class="wp-image-38372 size-full jetpack-lazy-image" src="../Images/2818bdb33a43a87592177b249771aa87.png" alt="Try Catch JavaScript Error Fail Message" data-lazy-srcset="https://blog.logrocket.com/wp-content/uploads/2021/03/try-catch-javascript-error-fail-message.png 730w, https://blog.logrocket.com/wp-content/uploads/2021/03/try-catch-javascript-error-fail-message-300x89.png 300w" data-lazy-sizes="(max-width: 730px) 100vw, 730px" data-lazy-src="https://blog.logrocket.com/wp-content/uploads/2021/03/try-catch-javascript-error-fail-message.png?is-pending-load=1" srcset="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-original-src="https://blog.logrocket.com/wp-content/uploads/2021/03/try-catch-javascript-error-fail-message.png"/><noscript><img data-lazy-fallback="1" data-attachment-id="38372" data-permalink="https://blog.logrocket.com/handling-javascript-errors-react-error-boundaries/try-catch-javascript-error-fail-message/" data-orig-file="https://blog.logrocket.com/wp-content/uploads/2021/03/try-catch-javascript-error-fail-message.png" data-orig-size="730,216" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="try-catch-javascript-error-fail-message" data-image-description="" data-image-caption="&lt;p&gt;This error fallback UI has been clipped to show the relevant part. Dismiss the error UI to view the normal state of the application.&lt;/p&gt;&#10;" data-medium-file="https://blog.logrocket.com/wp-content/uploads/2021/03/try-catch-javascript-error-fail-message-300x89.png" data-large-file="https://blog.logrocket.com/wp-content/uploads/2021/03/try-catch-javascript-error-fail-message.png" decoding="async" loading="lazy" class="wp-image-38372 size-full" src="../Images/2818bdb33a43a87592177b249771aa87.png" alt="Try Catch JavaScript Error Fail Message" srcset="https://blog.logrocket.com/wp-content/uploads/2021/03/try-catch-javascript-error-fail-message.png 730w, https://blog.logrocket.com/wp-content/uploads/2021/03/try-catch-javascript-error-fail-message-300x89.png 300w" sizes="(max-width: 730px) 100vw, 730px" data-original-src="https://blog.logrocket.com/wp-content/uploads/2021/03/try-catch-javascript-error-fail-message.png"/></noscript><figcaption id="caption-attachment-38372" class="wp-caption-text">This error fallback UI has been clipped to show the relevant part. Dismiss the error UI to view the normal state of the application.</figcaption></figure>
<p>需要注意的是，上述错误只会在开发过程中出现。在生产中，用户界面将被破坏，用户将看到一个空白屏幕。我们如何解决这个问题？输入误差界限。</p>
<blockquote><p><strong> N.B. </strong>，像 create-react-app 和 Next.js 这样的工具都有一个错误叠加组件，每当有错误的时候就会阻塞 UI，遮住你自己的错误边界。在本教程使用的 create-react-app 中，我们需要关闭右上角带有<strong> X </strong>标记的覆盖图，以查看我们自己使用的错误边界。</p></blockquote>
<h2 id="h2usingerrorboundariesinreact">在 React 中使用错误边界</h2>
<p>错误边界是 React 组件，它提供了一种方式来优雅地处理 React 组件中的 JavaScript 错误。有了它们，我们可以捕捉组件中的 JavaScript 运行时错误，处理这些错误，并显示一个后备 UI。</p>
<pre>import ErrorBoundary from "error-boundary";

function Users() {
  return (
    &lt;div&gt;
      &lt;ErrorBoundary&gt;
        {/* the rest of your application */}
      &lt;/ErrorBoundary/&gt;
    &lt;/div&gt;
  )
}
</pre>
<p>错误边界的操作类似于 JavaScript <code>try...catch</code>语句中的<code>catch</code>块，但有几个例外:它们是声明性的，或许不用说，只捕捉 React 组件中的错误。</p>
<p>更具体地说，它们在渲染阶段和生命周期方法中捕捉子组件中的错误。在错误边界的任何子组件中抛出的错误将被委托给组件树中最近的错误边界。</p>
<p>相比之下，错误边界不会捕捉发生在以下位置的错误:</p>
<ul>
<li><a href="https://reactjs.org/docs/error-boundaries.html#how-about-event-handlers">事件处理程序</a></li>
<li>异步代码</li>
<li>服务器端渲染</li>
<li>错误边界本身引发的错误</li>
</ul>
<p>对于充当误差边界的组件，有一些规则要遵循:</p>
<ol>
<li>它必须是一个类组件</li>
<li>它必须定义生命周期方法<code><a href="https://blog.logrocket.com/react-reference-guide-react-component/#fromerror">static getDerivedStateFromError()</a></code>或<code><a href="https://blog.logrocket.com/react-reference-guide-react-component/#didcatch">componentDidCatch()</a></code>中的一个或两个</li>
</ol>
<p>经验法则是，<code>static getDerivedStateFromError()</code>应该用于在抛出错误后呈现回退 UI，而<code>componentDidCatch()</code>应该用于记录这些错误。</p>
<p>下面的<code>&lt;PublicationErrorBoundary/&gt;</code>分量是一个误差边界，因为它满足必要的标准:</p>
<pre>class PublicationErrorBoundary extends Component {
  state = { error: false, errorMessage: '' };

  static getDerivedStateFromError(error) {
    // Update state to render the fallback UI
    return { error: true, errorMessage: error.toString() };
  }

  componentDidCatch(error, errorInfo) {
    // Log error to an error reporting service like Sentry
    console.log({ error, errorInfo });
  }

  render() {
    const { error, errorMessage } = this.state;
    const { children } = this.props;

    return error ? &lt;ErrorFallbackUI {...{ error, errorMessage }} /&gt; : children;
  }
}
</pre>
<p><code>&lt;PublicationErrorBoundary/&gt;</code>用以下更新替换上述<code>&lt;Publications/&gt;</code>组件中的<code>try...catch</code>模块:</p>
<pre>function Publications({ publications }) {
  return publications.map((publication, index) =&gt; (
    &lt;div key={index}&gt;
      &lt;PublicationErrorBoundary&gt;
        &lt;Publication {...{ publication }} /&gt;
      &lt;/PublicationErrorBoundary&gt;
    &lt;/div&gt;
  ));
}
</pre>
<p>现在，<code>&lt;Publication/&gt;</code>试图大写每个出版物标题时抛出的错误允许<a href="https://blog.logrocket.com/elegant-error-handling-javascript-either-monad/">进行优雅的异常处理</a>。错误已被隔离，并显示了回退用户界面。</p>
<figure id="attachment_38374" aria-describedby="caption-attachment-38374" class="wp-caption aligncenter"><img data-attachment-id="38374" data-permalink="https://blog.logrocket.com/handling-javascript-errors-react-error-boundaries/publication-typeerror-graceful-exception-handling-fallback-ui/" data-orig-file="https://blog.logrocket.com/wp-content/uploads/2021/03/publication-typeerror-graceful-exception-handling-fallback-UI.png" data-orig-size="730,572" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="publication-typeerror-graceful-exception-handling-fallback-UI" data-image-description="" data-image-caption="&lt;p&gt;App UI with error boundary and a fallback UI.&lt;/p&gt;&#10;" data-medium-file="https://blog.logrocket.com/wp-content/uploads/2021/03/publication-typeerror-graceful-exception-handling-fallback-UI-300x235.png" data-large-file="https://blog.logrocket.com/wp-content/uploads/2021/03/publication-typeerror-graceful-exception-handling-fallback-UI.png" decoding="async" class="wp-image-38374 size-full jetpack-lazy-image" src="../Images/630699bae1f484aec6332aa85f89c939.png" alt="Publication Typeerror Graceful Exception Handling Fallback UI" data-lazy-srcset="https://blog.logrocket.com/wp-content/uploads/2021/03/publication-typeerror-graceful-exception-handling-fallback-UI.png 730w, https://blog.logrocket.com/wp-content/uploads/2021/03/publication-typeerror-graceful-exception-handling-fallback-UI-300x235.png 300w" data-lazy-sizes="(max-width: 730px) 100vw, 730px" data-lazy-src="https://blog.logrocket.com/wp-content/uploads/2021/03/publication-typeerror-graceful-exception-handling-fallback-UI.png?is-pending-load=1" srcset="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-original-src="https://blog.logrocket.com/wp-content/uploads/2021/03/publication-typeerror-graceful-exception-handling-fallback-UI.png"/><noscript><img data-lazy-fallback="1" data-attachment-id="38374" data-permalink="https://blog.logrocket.com/handling-javascript-errors-react-error-boundaries/publication-typeerror-graceful-exception-handling-fallback-ui/" data-orig-file="https://blog.logrocket.com/wp-content/uploads/2021/03/publication-typeerror-graceful-exception-handling-fallback-UI.png" data-orig-size="730,572" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="publication-typeerror-graceful-exception-handling-fallback-UI" data-image-description="" data-image-caption="&lt;p&gt;App UI with error boundary and a fallback UI.&lt;/p&gt;&#10;" data-medium-file="https://blog.logrocket.com/wp-content/uploads/2021/03/publication-typeerror-graceful-exception-handling-fallback-UI-300x235.png" data-large-file="https://blog.logrocket.com/wp-content/uploads/2021/03/publication-typeerror-graceful-exception-handling-fallback-UI.png" decoding="async" loading="lazy" class="wp-image-38374 size-full" src="../Images/630699bae1f484aec6332aa85f89c939.png" alt="Publication Typeerror Graceful Exception Handling Fallback UI" srcset="https://blog.logrocket.com/wp-content/uploads/2021/03/publication-typeerror-graceful-exception-handling-fallback-UI.png 730w, https://blog.logrocket.com/wp-content/uploads/2021/03/publication-typeerror-graceful-exception-handling-fallback-UI-300x235.png 300w" sizes="(max-width: 730px) 100vw, 730px" data-original-src="https://blog.logrocket.com/wp-content/uploads/2021/03/publication-typeerror-graceful-exception-handling-fallback-UI.png"/></noscript><figcaption id="caption-attachment-38374" class="wp-caption-text">App UI with error boundary and a fallback UI.</figcaption></figure>
<p>你可以在<a href="https://codesandbox.io/s/react-error-boundary-zswhk?file=/src/App.js"> CodeSandbox </a>上看到这个例子。</p>
<h2 id="h2wheretoplaceerrorboundariesinthecomponenttree">在组件树中放置错误边界的位置</h2>
<p>Next.js 文档很好地解释了<a href="https://nextjs.org/docs/basic-features/fast-refresh#runtime-errors">一般的经验法则</a>:错误边界不应该太细；它们由 React 在生产中使用，并且应该总是有意设计的。</p>
<p>错误边界是特殊的 React 组件，应该仅在适当的时候用于捕捉错误。可以在应用程序的不同部分使用不同的错误边界来处理上下文错误，尽管它们可以是通用的，例如，网络连接错误边界。</p>
<p>注意，在前面的例子中，<code>Publications</code>中使用的是<code>&lt;PublicationErrorBoundary/&gt;</code>，而不是<code>Publication</code>。如果以其他方式使用，那么<code>&lt;PublicationErrorBoundary/&gt;</code>不会捕捉到试图大写每个出版物标题时抛出的错误，因为<code>&lt;PublicationErrorBoundary/&gt;</code>的子节点将是一个超链接，而不是一个组件。然而，在<code>&lt;Publications/&gt;</code>中使用它解决了这个问题。</p>
<pre>// This won't work because the children of `PublicationErrorBoundary`
// aren't components
function Publication({ publication }) {
  return (
    &lt;PublicationErrorBoundary&gt;
      &lt;a href={publication.href} className="article-cta"&gt;
        &lt;h3 className="title"&gt;{publication.title.toUpperCase()}&lt;/h3&gt;
        &lt;h3 className="info"&gt;{publication.lead}&lt;/h3&gt;
      &lt;/a&gt;
    &lt;/PublicationErrorBoundary&gt;
  );
}
</pre>
<p>另外，请注意，每个发布都有一个错误边界来监听它是否出错。如果至少有一个出版物有错误，那么不显示任何出版物是有意义的，那该怎么办呢？<code>&lt;Publications/&gt;</code>可以更新:</p>
<pre>// Before
function Publications({ publications }) {
  return publications.map((publication, index) =&gt; (
    &lt;div key={index}&gt;
      &lt;PublicationErrorBoundary&gt;
        &lt;Publication {...{ publication }} /&gt;
      &lt;/PublicationErrorBoundary&gt;
    &lt;/div&gt;
  ));
}

// After. Notice the location of `PublicationErrorBoundary`
function Publications({ publications }) {
  return (
    &lt;PublicationErrorBoundary&gt;
      {publications.map((publication, index) =&gt; (
        &lt;div key={index}&gt;
          &lt;Publication {...{ publication }} /&gt;
        &lt;/div&gt;
      ))}
    &lt;/PublicationErrorBoundary&gt;
  );
}
</pre>
<p>用户界面将被更新以显示回退用户界面:</p>
<p><img data-attachment-id="38377" data-permalink="https://blog.logrocket.com/handling-javascript-errors-react-error-boundaries/error-boundary-fallback-ui-updated-notice/" data-orig-file="https://blog.logrocket.com/wp-content/uploads/2021/03/error-boundary-fallback-ui-updated-notice.png" data-orig-size="730,125" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="error-boundary-fallback-ui-updated-notice" data-image-description="" data-image-caption="" data-medium-file="https://blog.logrocket.com/wp-content/uploads/2021/03/error-boundary-fallback-ui-updated-notice-300x51.png" data-large-file="https://blog.logrocket.com/wp-content/uploads/2021/03/error-boundary-fallback-ui-updated-notice.png" decoding="async" class="aligncenter wp-image-38377 size-full jetpack-lazy-image" src="../Images/35de45cdde6418591de4eb71eac2abac.png" alt="Error Boundary Fallback UI Updated Notice" data-lazy-srcset="https://blog.logrocket.com/wp-content/uploads/2021/03/error-boundary-fallback-ui-updated-notice.png 730w, https://blog.logrocket.com/wp-content/uploads/2021/03/error-boundary-fallback-ui-updated-notice-300x51.png 300w" data-lazy-sizes="(max-width: 730px) 100vw, 730px" data-lazy-src="https://blog.logrocket.com/wp-content/uploads/2021/03/error-boundary-fallback-ui-updated-notice.png?is-pending-load=1" srcset="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-original-src="https://blog.logrocket.com/wp-content/uploads/2021/03/error-boundary-fallback-ui-updated-notice.png"/></p><noscript><img data-lazy-fallback="1" data-attachment-id="38377" data-permalink="https://blog.logrocket.com/handling-javascript-errors-react-error-boundaries/error-boundary-fallback-ui-updated-notice/" data-orig-file="https://blog.logrocket.com/wp-content/uploads/2021/03/error-boundary-fallback-ui-updated-notice.png" data-orig-size="730,125" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="error-boundary-fallback-ui-updated-notice" data-image-description="" data-image-caption="" data-medium-file="https://blog.logrocket.com/wp-content/uploads/2021/03/error-boundary-fallback-ui-updated-notice-300x51.png" data-large-file="https://blog.logrocket.com/wp-content/uploads/2021/03/error-boundary-fallback-ui-updated-notice.png" decoding="async" loading="lazy" class="aligncenter wp-image-38377 size-full" src="../Images/35de45cdde6418591de4eb71eac2abac.png" alt="Error Boundary Fallback UI Updated Notice" srcset="https://blog.logrocket.com/wp-content/uploads/2021/03/error-boundary-fallback-ui-updated-notice.png 730w, https://blog.logrocket.com/wp-content/uploads/2021/03/error-boundary-fallback-ui-updated-notice-300x51.png 300w" sizes="(max-width: 730px) 100vw, 730px" data-original-src="https://blog.logrocket.com/wp-content/uploads/2021/03/error-boundary-fallback-ui-updated-notice.png"/></noscript>
<h2 id="h2errorboundarypropagation">误差边界传播</h2>
<p>类似于<code>catch</code>块的工作方式，如果一个错误边界试图呈现错误消息失败，错误将传播到它上面最近的错误边界。如果抛出的错误没有被任何错误边界捕获，整个组件树将被卸载。</p>
<p>这是从 React 16 开始的<a href="https://reactjs.org/docs/error-boundaries.html#new-behavior-for-uncaught-errors">新行为，理由是完全移除损坏的 UI 比将其留在原处更好，并且在出现错误时提供更好的用户体验。</a></p>
<pre>&lt;AppErrorBoundary&gt;
  &lt;App&gt;
    &lt;PublicationsErrorBoundary&gt;
      &lt;Publications&gt;
        &lt;PublicationErrorBoundary&gt;
          &lt;Publication /&gt;
        &lt;PublicationErrorBoundary&gt;
      &lt;/Publications&gt;
    &lt;/PublicationsErrorBoundary&gt;
  &lt;/App&gt;
&lt;/AppErrorBoundary&gt;
</pre>
<p>以上面人为的组件树为例。如果在<code>&lt;Publication/&gt;</code>中捕捉到错误，最近的错误边界<code>&lt;PublicationErrorBoundary/&gt;</code>将对此负责。如果它不能履行自己的职责，<code>&lt;PublicationsErrorBoundary/&gt;</code>将作为后备力量。如果同样失败，<code>&lt;AppErrorBoundary/&gt;</code>将尝试在组件完全卸载之前处理错误。</p>
<h2 id="h2resettingerrorboundaries">重置误差边界</h2>
<p>这是我在使用错误边界时发现的边缘情况之一。通常，这是通过重置 UI 状态并从损坏中恢复 UI 来完成的。</p>
<p>假设用户失去连接，并且连接错误边界已经成功地显示回退 UI，提醒用户检查他们的连接。当连接状态变为活动时，我们可以恢复 UI 吗？简单的回答是可以，另外就是看情况。</p>
<p>错误可能是棘手的、动态的和不确定的，您最好研究一下数据获取工具，如 SWR 或 React Query，或<a href="https://blog.logrocket.com/error-handling-react-error-boundary">React-error-boundary package</a>，它们可以缓解这类问题。</p>
<h2 id="h2conclusion">结论</h2>
<p>只要这样做是合理的，就应该使用错误边界来处理 React 应用程序中的运行时错误。你和他们越熟悉，你就越明白他们存在的理由。</p>
<p>特别是有了 react-error-boundary 包，您可以减少冗余代码的数量和您遇到的经过良好测试的抽象的不确定性——正如 Kent Dodds 所说的那样，这是任何人都需要的最后一个错误边界组件。</p><div class="code-block code-block-17">
<div class="blog-plug inline-plug react-plug" vwo-el-id="26283398190">
<h2 vwo-el-id="41600691720"><a href="https://lp.logrocket.com/blg/react-signup-general" target="_blank" rel="noopener"> LogRocket </a>:全面了解您的生产 React 应用</h2><p>调试 React 应用程序可能很困难，尤其是当用户遇到难以重现的问题时。如果您对监视和跟踪 Redux 状态、自动显示 JavaScript 错误以及跟踪缓慢的网络请求和组件加载时间感兴趣，</p><a href="https://lp.logrocket.com/blg/react-signup-general" target="_blank" vwo-el-id="19356441070">try LogRocket</a><p>. </p><a class="signup" href="https://lp.logrocket.com/blg/react-signup-general" target="_blank" rel="noopener noreferrer" vwo-el-id="19356441380">
<img class="first-react-image alignnone size-full wp-image-46 jetpack-lazy-image jetpack-lazy-image--handled" src="../Images/f300c244a1a1cf916df8b4cb02bec6c6.png" vwo-el-id="18272717540" data-lazy-loaded="1" data-original-src="https://files.readme.io/27c94e7-Image_2017-06-05_at_9.46.04_PM.png"/>
</a>
<a class="signup" href="https://lp.logrocket.com/blg/react-signup-general" target="_blank" rel="noopener noreferrer" vwo-el-id="19356441690">
<img class="second-react-image alignnone size-full wp-image-46 jetpack-lazy-image jetpack-lazy-image--handled" src="../Images/d6f5a5dd739296c1dd7aab3d5e77eeb9.png" alt="LogRocket Dashboard Free Trial Banner" vwo-el-id="30720362350" data-lazy-loaded="1" data-original-src="https://blog.logrocket.com/wp-content/uploads/2017/03/1d0cd-1s_rmyo6nbrasp-xtvbaxfg.png"/>
</a>
<p vwo-el-id="28675660440" class="">LogRocket 结合了会话回放、产品分析和错误跟踪，使软件团队能够创建理想的 web 和移动产品体验。这对你来说意味着什么？</p>
<p>LogRocket 不是猜测错误发生的原因，也不是要求用户提供截图和日志转储，而是让您回放问题，就像它们发生在您自己的浏览器中一样，以快速了解哪里出错了。</p>
<p>不再有嘈杂的警报。智能错误跟踪允许您对问题进行分类，然后从中学习。获得有影响的用户问题的通知，而不是误报。警报越少，有用的信号越多。</p>
<p vwo-el-id="28675660750">LogRocket Redux 中间件包为您的用户会话增加了一层额外的可见性。LogRocket 记录 Redux 存储中的所有操作和状态。</p>
<p vwo-el-id="28675661060">现代化您调试 React 应用的方式— <a class="signup" href="https://lp.logrocket.com/blg/react-signup-general" target="_blank" rel="noopener noreferrer" vwo-el-id="40093418840">开始免费监控</a>。</p>
</div></div>

<p class="clearfix"/>
<p class="clearfix"/>
</article>

</div>    
</body>
</html>