<html>
<head>
<title>Error handling in Go: Best practices - LogRocket Blog</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1>Go中的错误处理:最佳实践- LogRocket博客</h1>
<blockquote>原文：<a href="https://blog.logrocket.com/error-handling-golang-best-practices/#0001-01-01">https://blog.logrocket.com/error-handling-golang-best-practices/#0001-01-01</a></blockquote><div><article class="article-post">
<p><em> <strong>编者按</strong>:这篇文章最后一次更新和准确性验证是在2022年11月18日。</em></p>
<p>处理Go中的错误需要一种不同于其他主流编程语言的传统方法，比如JavaScript，它使用了<code>try...catch</code>语句，或者Python使用了它的<code>try… except</code>块。开发人员经常误用Go的特性来处理错误。</p>
<p>在本文中，我们将考虑您在处理Go应用程序中的错误时应该遵循的最佳实践。为了理解本文，您需要对Go如何工作有一个基本的了解。我们开始吧！</p>

<h2 id="the-blank-identifier">空白标识符</h2>
<p><a href="https://golang.org/doc/effective_go.html#blank">空白标识符</a>是一个匿名占位符。您可以像在声明中使用任何其他标识符一样使用它，但是它不引入绑定。空白标识符提供了一种方法来忽略赋值中的左手值，并避免程序中未使用的导入和变量周围的编译器错误。</p>
<p>将错误赋给空白标识符而不是正确处理它们是不安全的，这意味着您已经决定显式忽略已定义函数的值:</p>
<pre class="language-go hljs">result, _ := iterate(x,y)

if value &gt; 0 {
  // ensure you check for errors before results.
}
</pre>
<p>这背后的基本原理可能是您不希望函数出错。但是，这可能会在程序中产生层叠效果。最佳实践是尽可能处理错误。</p>
<h2 id="handling-errors-through-multiple-return-values">通过多个返回值处理错误</h2>
<p>处理错误的一种方法是利用Go中的函数支持多个返回值这一事实。因此，您可以在定义函数的结果旁边传递一个错误变量:</p>
<pre class="language-go hljs">func iterate(x, y int) (int, error) {

}
</pre>
<p>在上面的代码片段中，如果我们认为函数有可能失败，我们必须返回预定义的<code>error</code>变量。<code>error</code>是在Go的<a href="https://pkg.go.dev/builtin@go1.19.2">内置包</a>中声明的接口类型，其零值为<code>nil</code>:</p>
<pre class="language-go hljs">type error interface {
   Error() string
 }
</pre>
<p>通常，返回一个<code>error</code>意味着有问题，返回<code>nil</code>意味着没有错误:</p>
<pre class="language-go hljs">result, err := iterate(x, y)
 if err != nil {
  // handle the error appropriately
 } else {
  // you're good to go
 }
</pre>
<p>每当调用<code>iterate</code>函数并且<code>err</code>不等于<code>nil</code>时，返回的错误应该得到适当的处理。</p>
<p>一种选择是创建一个重试或清理机制的实例。用这种方式处理错误的唯一缺点是没有Go编译器的强制。您必须决定您创建的函数如何返回错误。</p>
<p>您可以定义一个<code>error</code>结构并将它放在返回值的位置。一种方法是使用内置的<code>errorString</code>结构。你也可以在<a href="https://go.dev/src/errors/errors.go"> Go的源代码</a>中找到下面的代码:</p>
<pre class="language-go hljs">package errors

 func New(text string) error {
     return &amp;errorString {
         text
     }
 }

 type errorString struct {
     s string
 }

 func(e * errorString) Error() string {
     return e.s
 }
</pre>
<p>在上面的代码示例中，<code>errorString</code>嵌入了一个由<code>Error</code>方法返回的<code>string</code>。要创建自定义错误，您必须定义您的<code>error</code>结构，并使用<a href="https://golang.org/ref/spec#Method_sets">方法集</a>将一个函数关联到您的结构:</p>
<pre class="language-go hljs">// Define an error struct
type CustomError struct {
    msg string
}
// Create a function Error() string and associate it to the struct.
func(error * CustomError) Error() string {
    return error.msg
}
// Then create an error object using MyError struct.
func CustomErrorInstance() error {
    return &amp;CustomError {
        "File type not supported"
    }
}
</pre>
<p>然后，新创建的自定义错误可以被重新构造，以使用内置的<code>error</code>结构:</p>
<pre class="language-go hljs"> import "errors"
func CustomeErrorInstance() error {
    return errors.New("File type not supported")
}
</pre>
<p>内置的<code>error</code>结构的一个限制是它没有堆栈跟踪，这使得很难定位错误发生的位置。在打印出来之前，错误可能会通过许多函数。</p>
<p>要解决这个问题，您可以安装<code><a href="https://github.com/pkg/errors/blob/master/errors.go">pkg/errors</a></code>包，它提供了基本的错误处理原语，比如堆栈跟踪记录、错误包装、解包和格式化。要安装此软件包，请在您的终端中运行以下命令:</p>
<pre class="language-go hljs">go get github.com/pkg/errors
</pre>
<p>当您需要添加堆栈跟踪或任何其他信息来使调试错误更容易时，使用<code>New</code>或<code>Errorf</code>函数来提供记录您的堆栈跟踪的错误。<code>Errorf</code>实现了<a href="https://golang.org/pkg/fmt/#Formatter"> <code>fmt.Formatter</code> </a>接口，让你使用<code>fmt</code>包符文、<code>%s</code>、<code>%v</code>和<code>%+v</code>格式化你的错误:</p>
<pre class="language-go hljs">import(
    "github.com/pkg/errors"
    "fmt"
)
func X() error {
    return errors.Errorf("Could not write to file")
}

func customError() {
    return X()
}

func main() {
    fmt.Printf("Error: %+v", customError())
}
</pre>
<p>要打印堆栈跟踪而不是普通的错误消息，您必须在格式模式中使用<code>%+v</code>而不是<code>%v</code>。堆栈跟踪将类似于下面的代码示例:</p>
<pre class="language-go hljs">Error: Could not write to file
main.X
 /Users/raphaelugwu/Go/src/golangProject/error_handling.go:7
main.customError
 /Users/raphaelugwu/Go/src/golangProject/error_handling.go:15
main.main
 /Users/raphaelugwu/Go/src/golangProject/error_handling.go:19
runtime.main
 /usr/local/opt/go/libexec/src/runtime/proc.go:192
runtime.goexit
 /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:2471
</pre>
<h2 id="defer-panic-recover">推迟、恐慌和恢复</h2>
<p>虽然Go没有例外，但它有一种类似的机制，称为<a href="https://blog.golang.org/defer-panic-and-recover">延迟、死机和恢复</a>。Go的思想是，在JavaScript中添加像<code>try/catch/finally</code>语句这样的异常会导致复杂的代码，并鼓励程序员将太多的基本错误(如无法打开文件)标记为异常。</p>
<p>你不应该像使用<code>throw/catch/finally</code>一样使用<code>defer/panic/recover</code>。您应该只在出现意外的、不可恢复的故障时保留它。</p>
<p>Defer是一种将函数调用放入堆栈的语言机制。当主机函数完成时，每个延迟函数以相反的顺序执行，<a href="https://blog.logrocket.com/type-assertions-vs-type-conversions-go/">，而不管是否调用了紧急</a>。延迟机制对于清理资源非常有用:</p>
<pre class="language-go hljs">package main

import (
        "fmt"
)

func A() {
        defer fmt.Println("Keep calm!")
        B()
}
func B() {
        defer fmt.Println("Else...")
        C()
}
func C() {
        defer fmt.Println("Turn on the air conditioner...")
        D()
}
func D() {
        defer fmt.Println("If it's more than 30 degrees...")
}
func main() {
        A()
}
</pre>
<p>上面的代码将编译如下:</p>
<pre class="language-go hljs">If it's more than 30 degrees...
Turn on the air conditioner...
Else...
Keep calm!
</pre>
<p><code>panic</code>是停止正常执行流程的内置函数。当你在代码中调用<code>panic</code>时，意味着你已经决定你的调用者不能解决问题。因此，你应该只在极少数情况下使用<code>panic</code>,在那种情况下，你的代码或者任何集成你的代码的人继续下去都不安全。</p>
<p>下面的代码示例演示了<code>panic</code>的工作方式:</p>
<pre class="language-go hljs">package main

import (
        "errors"
        "fmt"
)

func A() {
        defer fmt.Println("Then we can't save the earth!")
        B()
}
func B() {
        defer fmt.Println("And if it keeps getting hotter...")
        C()
}
func C() {
        defer fmt.Println("Turn on the air conditioner...")
        Break()
}
func Break() {
        defer fmt.Println("If it's more than 30 degrees...")
        panic(errors.New("Global Warming!!!"))

}
func main() {
        A()
}
</pre>
<p>上面的示例将编译如下:</p>
<pre class="language-go hljs">If it's more than 30 degrees...
Turn on the air conditioner...
And if it keeps getting hotter...
Then we can't save the earth!
panic: Global Warming!!!

goroutine 1 [running]:
main.Break()
        /tmp/sandbox186240156/prog.go:22 +0xe0
main.C()
        /tmp/sandbox186240156/prog.go:18 +0xa0
main.B()
        /tmp/sandbox186240156/prog.go:14 +0xa0
main.A()
        /tmp/sandbox186240156/prog.go:10 +0xa0
main.main()
        /tmp/sandbox186240156/prog.go:26 +0x20

Program exited: status 2.
</pre>
<p>如上图，当<code>panic</code>被使用且未被处理时，执行流程停止，所有延迟的函数以相反的顺序执行，并打印堆栈跟踪。</p>
<p>您可以使用内置的<code>recover</code>函数来处理<code>panic</code>并返回紧急调用传递的值。<code>recover</code>必须总是在<code>defer</code>函数中被调用，否则，它将返回<code>nil</code>:</p>
<pre class="language-go hljs">package main

import (
        "errors"
        "fmt"
)

func A() {
        defer fmt.Println("Then we can't save the earth!")
        defer func() {
                if x := recover(); x != nil {
                        fmt.Printf("Panic: %+v\n", x)
                }
        }()
        B()
}
func B() {
        defer fmt.Println("And if it keeps getting hotter...")
        C()
}
func C() {
        defer fmt.Println("Turn on the air conditioner...")
        Break()
}
func Break() {
        defer fmt.Println("If it's more than 30 degrees...")
        panic(errors.New("Global Warming!!!"))

}
func main() {
        A()
}
</pre>
<p>正如您在上面的代码示例中看到的，<code>recover</code>防止了整个执行流程停止。我们添加了一个<code>panic</code>函数，因此编译器将返回以下内容:</p>
<pre class="language-go hljs">If it's more than 30 degrees...
Turn on the air conditioner...
And if it keeps getting hotter...
Panic: Global Warming!!!
Then we can't save the earth!

Program exited.
</pre>
<p>要将错误报告为返回值，必须在调用<code>panic</code>函数的同一个goroutine 中调用<a href="https://blog.logrocket.com/concurrency-patterns-golang-waitgroups-goroutines/"> <code>recover</code>函数，从<code>recover</code>函数中检索一个错误结构，并将其传递给一个变量:</a></p>
<pre class="language-go hljs">package main

import (
        "errors"
        "fmt"
)

func saveEarth() (err error) {

        defer func() {
                if r := recover(); r != nil {
                        err = r.(error)
                }
        }()
        TooLate()
        return
}
func TooLate() {
        A()
        panic(errors.New("Then there's nothing we can do"))
}

func A() {
        defer fmt.Println("If it's more than 100 degrees...")
}
func main() {
        err := saveEarth()
        fmt.Println(err)
}
</pre>
<p>每个延迟函数都将在函数调用之后、return语句之前执行。因此，您可以在执行return语句之前设置返回的变量。上面的代码示例将编译如下:</p>
<pre class="language-go hljs">If it's more than 100 degrees...
Then there's nothing we can do

Program exited.
</pre>
<h2 id="error-wrapping">错误包装</h2>
<p>以前，Go中的错误包装只能通过像<code>pkg/errors</code>这样的包来访问。然而，<a href="https://go.dev/doc/go1.13"> Go v1.13引入了对错误包装</a>的支持。</p>
<p>根据<a href="https://golang.org/doc/go1.13#error_wrapping">发布说明</a>:</p>
<blockquote><p>一个错误<code>e</code>可以通过提供一个返回<code>w</code>的<code>Unwrap</code>方法来包装另一个错误<code>w</code>。程序可以使用<code>e</code>和<code>w</code>，允许<code>e</code>为<code>w</code>提供额外的上下文或者重新解释它，同时仍然允许程序基于<code>w</code>做出决定。</p></blockquote>
<p>为了创建包装的错误，<code>fmt.Errorf</code>有一个<code>%w</code>动词，为了检查和解开错误，<code>error</code>包中增加了几个函数。</p>
<p><code>errors.Unwrap</code>基本上是检查和暴露程序中的潜在错误。如果<code>Err</code>的类型包含返回错误的<code>Unwrap</code>方法，它将返回在<code>Err</code>上调用<code>Unwrap</code>方法的结果。否则，<code>Unwrap</code>返回0:</p>
<pre class="language-go hljs">package errors

type Wrapper interface{
  Unwrap() error
}
</pre>
<p>下面是<code>Unwrap</code>方法的一个实现示例:</p>
<pre class="language-go hljs">func(e*PathError)Unwrap()error{
  return e.Err
}
</pre>
<p>使用<code>errors.Is</code>功能，您可以将误差值与标记值进行比较。</p>
<p>该函数不是将sentinel值与一个错误进行比较，而是将其与错误链中的每个错误进行比较。它还对一个错误实现了一个<code>Is</code>方法，这样一个错误即使不是一个标记值也可以把它自己作为一个标记发布:</p>
<pre class="language-go hljs">func Is(err, target error) bool
</pre>
<p>在上面的基本实现中，<code>Is</code>检查并报告<code>err</code>或其链中的任何<code>errors</code>是否等于目标值，即标记值。</p>
<p><code>errors.As</code>函数提供了一种转换成特定错误类型的方法。它在错误链中寻找匹配sentinel值的第一个错误，如果找到，它将sentinel值设置为该错误值，返回<code>true</code>:</p>
<pre class="language-go hljs">package main

import (
        "errors"
        "fmt"
        "os"
)

func main() {
        if _, err := os.Open("non-existing"); err != nil {
                var pathError *os.PathError
                if errors.As(err, &amp;pathError) {
                        fmt.Println("Failed at path:", pathError.Path)
                } else {
                        fmt.Println(err)
                }
        }

}
</pre>
<p>你可以在<a href="https://golang.org/pkg/errors/#As"> Go的源代码</a>中找到这段代码。以下是编译结果:</p>
<pre class="language-go hljs">Failed at path: non-existing

Program exited.
</pre>
<p>如果错误的具体值可赋给标记值所指向的值，则该错误与标记值匹配。如果sentinel值不是指向实现error的类型或任何接口类型的非零指针，则<code>As</code>将会出错。如果<code>err</code>为<code>nil</code>，则<code>As</code>返回false。</p>
<h2 id="summary">摘要</h2>
<p>Go社区最近在支持各种编程概念方面取得了令人印象深刻的进步，并引入了更简洁和简单的方法来处理错误。你对如何处理或处理围棋程序中可能出现的错误有什么想法吗？请在下面的评论中告诉我。</p><div class="code-block code-block-2">
<div class="blog-plug base-cta"><h2>使用<a class="signup" href="https://lp.logrocket.com/blg/signup" target="_blank" rel="noopener noreferrer"> LogRocket </a>消除传统错误报告的干扰</h2>
<a href="https://lp.logrocket.com/blg/signup" class="signup" target="_blank" rel="noopener noreferrer"><img class="alignnone size-full wp-image-46 jetpack-lazy-image" src="../Images/d6f5a5dd739296c1dd7aab3d5e77eeb9.png" alt="LogRocket Dashboard Free Trial Banner" data-lazy-src="https://blog.logrocket.com/wp-content/uploads/2017/03/1d0cd-1s_rmyo6nbrasp-xtvbaxfg.png?is-pending-load=1" srcset="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-original-src="https://blog.logrocket.com/wp-content/uploads/2017/03/1d0cd-1s_rmyo6nbrasp-xtvbaxfg.png"/><noscript><img data-lazy-fallback="1" class="alignnone size-full wp-image-46" src="../Images/d6f5a5dd739296c1dd7aab3d5e77eeb9.png" alt="LogRocket Dashboard Free Trial Banner" data-original-src="https://blog.logrocket.com/wp-content/uploads/2017/03/1d0cd-1s_rmyo6nbrasp-xtvbaxfg.png"/></noscript></a>
<p><a href="https://lp.logrocket.com/blg/signup" target="_blank" rel="noopener noreferrer"> LogRocket </a>是一个数字体验分析解决方案，它可以保护您免受数百个假阳性错误警报的影响，只针对几个真正重要的项目。LogRocket会告诉您应用程序中实际影响用户的最具影响力的bug和UX问题。</p>
<p>然后，使用具有深层技术遥测的会话重放来确切地查看用户看到了什么以及是什么导致了问题，就像你在他们身后看一样。</p>
<p>LogRocket自动聚合客户端错误、JS异常、前端性能指标和用户交互。然后LogRocket使用机器学习来告诉你哪些问题正在影响大多数用户，并提供你需要修复它的上下文。</p>
<p>关注重要的bug—<a class="signup" href="https://lp.logrocket.com/blg/signup-issue-free" target="_blank" rel="noopener noreferrer">今天就试试LogRocket】。</a></p></div></div>

<p class="clearfix"/>
<p class="clearfix"/>
</article>

</div>    
</body>
</html>